[FIXED] Lint error `InvalidFragmentVersionForActivityResult`
This is result of New Features added in androidx.activity:activity-ktx Version 1.2.0-alpha07

Added a new InvalidFragmentVersionForActivityResult lint check that verifies that you are using Fragment 1.3.0-alpha07 when using the Activity Result API, avoiding runtime crashes due to “invalid request code” issues and non-functioning permission requests caused by using older versions of Fragments. (b/152554847)

```
  Errors found:

  /Users/hossain/development/repos/hossains/android-hk-vision-muzei-plugin/app/src/main/java/com/hossainkhan/vision/HkVisionRedirectActivity.kt:46: Error: Upgrade Fragment version to at least 1.3.0-alpha07. [InvalidFragmentVersionForActivityResult]
      private val requestLauncher = registerForActivityResult(StartActivityForResult()) {

```